name: Build AR.js
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            aframe/build
            three.js/build
      - name: Deploy to GitHub Pages
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master' # only deploy on master branch pushes
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages # The branch the action should deploy to.
          build_dir: examples # The folder the action should deploy.
          # GITHUB_TOKEN secret is required unless a personal access token is used.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
